### PR TITLE
Don't overwrite configuration with routing data.

### LINKED ISSUE #258: Note about Azure SQL DB v12 Support in 1.8.1 or higher
A couple of people in Azure have included me on incidents where folks were trying to use old tedious drivers with their v12 platform and it gets escalated to their engineering team. Is it a good idea to put a note under ["SQL Server Support"](http://pekim.github.io/tedious/index.html) to alert people to this?

### LINKED ISSUE #262: Changes port number to 11024 in Azure
After connection is established the original connection string (`config`) is modified, `config.options.port` is set to `11024` thus all subsequent connections using this `config` var fail with a timeout.

This only happens when code is executed in Azure Web App. Wasn't able to reproduce in locally a local environment, connecting to the exact same database.

Perhaps it's related to re-route which may work differently when connection is established from Azure datacenter vs from outside network.

### PR DESCRIPTION
**Pull request by arthurschreiber**
This fixes #262, #307 and #269. I also believe it fixes #258.

It's a bit simpler than the fix proposed in #269, and passes all unit and integration tests.

I can push a beta package to npm with this fix in place, if anyone is interested in testing this. I'll release `1.11.5` including this fix and I'll port the fix to 1.12 and the `master` branch once someone confirms this is working for them.

//cc @gleeds @bretcope @tysjiang @SyRenity @spanditcaa PTAL

### CODE REVIEW

**Comment by arthurschreiber** [comment]
This should also fix #307.

**Comment by spanditcaa** [comment]
Thanks @arthurschreiber we would be happy to help test.

**Comment by arthurschreiber** [comment]
@spanditcaa Let me go ahead and merge this. I'll push a beta release in a few minutes.

**Comment by arthurschreiber** [comment]
@spanditcaa I just pushed `tedious@1.11.5-beta.2-g2780aac`. Please let me know if that version works for you.

**Comment by gleeds** [comment]
@arthurschreiber I'll test this in my environment too.

**Comment by gleeds** [comment]
This fails for me with the following error:
```
{ [ConnectionError: Database 'MYDATABASENAME' on server '' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '{02AC65E1-3E6B-44D8-91A3-D6F977303E1F}'.]
  name: 'ConnectionError',
  message: 'Database \'MYDATABASENAME\' on server \'\' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of \'{02AC65E1-3E6B-44D8-91A3-D6F977303E1F}\'.',
  code: 'ELOGIN' }
```

I'm pretty sure the problem is that the `serverName` property in `sendLogin7Packet` needs to match the name of the server you are being redirected to, and not the initial server from your configuration.

**Comment by arthurschreiber** [comment]
@gleeds This is what @christopheranderson also described in https://github.com/pekim/tedious/issues/223, right? Let me take a look into what's going on.

**Pull request merged**
