### PR TITLE
Send correct servername in Login7 after rerouting

### PR DESCRIPTION
**Pull request by arthurschreiber**
In addition to #309.

I can push another beta package, just need some other pair of eyes looking over this.

//cc @gleeds @bretcope @tysjiang @SyRenity @spanditcaa PTAL

### CODE REVIEW

**Comment by arthurschreiber** [comment]
Appveyor build for 0.10 failed because of some unrelated issue. I'll merge this and tag a new beta release.

**Comment by spanditcaa** [comment]
will update and let you know what we find.

**Comment by arthurschreiber** [comment]
Published as `tedious@1.11.5-beta.5-gb7b6e4d`.

**Comment by gleeds** [comment]
I retested with this version, it seems like it has fixed the issue for me (#262).  I personally never ran into the #272, so I can't confirm if that is resolved.

**Comment by spanditcaa** [comment]
We're working with some Microsoft folks who were able to trigger a failover/reroute for us.  The driver restored connection as desired.

**Comment by spanditcaa** [comment]
However - this was from a host running outside the Azure datacenter.  It seems we aren't able to connect from a host running in Azure.  We're troubleshooting this now.  As I understand, there is a different connection path from internal to Azure datacenters.

**Comment by gleeds** [comment]
@spanditcaa I can only get the initial redirect when connecting from a host inside Azure, when I connect from a host outside of azure I never get redirected to another server (maybe because the other server isn't publicly routable?)

Another thing that keeps tripping me up is that I have tedious twice in the app I'm trying to test on (because I'm dumb), both in the root, and as a part of the mssql npm library, and I keep accidentally updating only one or the other.  Also the Kudu deployment thing seems to sporadically run npm update when I deploy.  You might double check your package.json for tedious on the deployed server to make sure it really is the right one.

**Comment by spanditcaa** [comment]
@gleeds @arthurschreiber  

We had what seems to be an unrelated deployment issue.  I ran a clean deployment in Azure and everything is working normally.  We also had another failover/reroute triggered and the hosts picked up the new servers and reconnected in about 200ms.

**Comment by arthurschreiber** [comment]
That sounds great. I'm really glad the fix is working for you.

I'll need to polish the changes a bit and create some unit tests for this, and then I'll push new 1.11 and 1.12 releases containing the fix.

I won't get around to doing this today, but I hope I can find some time this weekend.

**Comment by arthurschreiber** [comment]
Everyone listening in on this, I released `1.11.5` and `1.12.3` containing this fix.

**Comment by spanditcaa** [comment]
Thanks @arthurschreiber.  I think 1.11.5 may need an npm publish.  I only see 1.12.3 added there.

**Comment by arthurschreiber** [comment]
@spanditcaa It should be available now. There's some issue with pushing to the npm registry using older  versions of the npm client, which caused the push from Travis to fail. I pushed the version manually for now.

**Pull request merged**
