### PR TITLE
Release Proposal: 1.11.2

### PR DESCRIPTION
**Pull request by arthurschreiber**
Included fixes:

* #275

### CODE REVIEW

**Comment by arthurschreiber** [comment]
@patriksimek I've seen you just release 1.11.1. Can we do another release that includes #275 as well?

**Comment by patriksimek** [comment]
Sure. You want me to do it?

**Comment by arthurschreiber** [comment]
Sure, if you could get that done, that'd be great. Otherwise let me know and I'll push up a new version myself.

**Comment by arthurschreiber** [comment]
Sweet, thank you very much! :heart:

**Pull request merged**
